### ISSUE TITLE
Regarding the issue mentioned in a review at AMO

### ISSUE THREAD

**Issue by ghost** [jmozmoz/pdfViewerSwitcher#1]
I just saw [this review](https://addons.mozilla.org/nl/firefox/addon/pdfviewerswitcher/reviews/502204/) at AMO. I think this problem might be due to the web site using the [`Content-Disposition: attachment`](https://startpage.com/do/search?cmd=process_search&cat=web&query=content+disposition+attachment) header. If I remember it correctly, PDF.js won't display the file and prompt for download instead if this header is set.

This might explain the problem the user is seeing.

**Comment by jmozmoz** [comment]
Unfortunately I do not really understand that bug report (at AMO). And the bug reporter did not give more infos.
